// Code generated by generate_schema_tables.go DO NOT EDIT.

package tables

import (
	"bytes"
	"fmt"

	"github.com/ngalayko/url_shortner/server/dao"
	"github.com/ngalayko/url_shortner/server/logger"
	"github.com/ngalayko/url_shortner/server/schema"
)

type LinkTable struct {
	db     *dao.Db
	logger *logger.Logger
}

func (l *LinkTable) Insert(ll []*schema.Link) error {
	return l.db.Mutate(func(tx *dao.Tx) error {

		b := bytes.Buffer{}

		b.WriteString("INSERT INTO links" +
			"(user_id, url, short_url, clicks, views, expired_at, created_at, deleted_at)" +
			"VALUES")

		for _, l := range ll {
			b.WriteString(
				fmt.Sprintf("(%v, %v, %v, %v, %v, %v, %v, %v)",
					l.UserID,
					l.URL,
					l.ShortURL,
					l.Clicks,
					l.Views,
					l.ExpiredAt,
					l.CreatedAt,
					l.DeletedAt))
		}

		_, err := tx.Exec(b.String())
		return err
	})
}
