// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package migrate

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type migrationTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *migrationTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("migrations").
func (v *migrationTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *migrationTableType) Columns() []string {
	return []string{"id", "name", "applied_at"}
}

// NewStruct makes a new struct for that view or table.
func (v *migrationTableType) NewStruct() reform.Struct {
	return new(migration)
}

// NewRecord makes a new record for that table.
func (v *migrationTableType) NewRecord() reform.Record {
	return new(migration)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *migrationTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// migrationTable represents migrations view or table in SQL database.
var migrationTable = &migrationTableType{
	s: parse.StructInfo{Type: "migration", SQLSchema: "", SQLName: "migrations", Fields: []parse.FieldInfo{{Name: "ID", Type: "uint", Column: "id"}, {Name: "Name", Type: "string", Column: "name"}, {Name: "AppliedAt", Type: "time.Time", Column: "applied_at"}}, PKFieldIndex: 0},
	z: new(migration).Values(),
}

// String returns a string representation of this struct or record.
func (s migration) String() string {
	res := make([]string, 3)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "AppliedAt: " + reform.Inspect(s.AppliedAt, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *migration) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.AppliedAt,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *migration) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.AppliedAt,
	}
}

// View returns View object for that struct.
func (s *migration) View() reform.View {
	return migrationTable
}

// Table returns Table object for that record.
func (s *migration) Table() reform.Table {
	return migrationTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *migration) PKValue() interface{} {
	return s.ID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *migration) PKPointer() interface{} {
	return &s.ID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *migration) HasPK() bool {
	return s.ID != migrationTable.z[migrationTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *migration) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.ID = uint(i64)
	} else {
		s.ID = pk.(uint)
	}
}

// check interfaces
var (
	_ reform.View   = migrationTable
	_ reform.Struct = (*migration)(nil)
	_ reform.Table  = migrationTable
	_ reform.Record = (*migration)(nil)
	_ fmt.Stringer  = (*migration)(nil)
)

func init() {
	parse.AssertUpToDate(&migrationTable.s, new(migration))
}
